bp-core/main/default/objects/Pitcher__c/Pitcher__c.object-meta.xml
<CustomObject>
    <label>Pitcher</label>
    <nameField>
        <label>Pitcher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pitchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bp-core/main/default/objects/Pitcher__c/fields/Throws__c.field-meta.xml
<CustomField>
    <fullName>Throws__c</fullName>
    <label>Throws</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Right</fullName>
                <default>true</default>
                <label>Right</label>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

bp-core/main/default/classes/PitchersSelector.cls
public inherited sharing class PitchersSelector extends ApplicationSelector  {
    public PitchersSelector() {

    }

    public List<Pitcher__c> selectById(Set<Id> pitcherIds) {
        return (List<Pitcher__c>)selectSObjectsById(pitcherIds);
    }

    public List<Pitcher__c> selectAll() {
        return (List<Pitcher__c>)Database.query(newQueryFactory().toSOQL());
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Pitcher__c.Id,
            Pitcher__c.Name,
            Pitcher__c.Throws__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Pitcher__c.sObjectType;
    }
}