bp-core/main/default/objects/Batter__c/Batter__c.object-meta.xml
<CustomObject>
    <label>Batter</label>
    <nameField>
        <label>Batter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Batter__c/fields/Outing__c.field-meta.xml
<CustomField>
    <fullName>Outing__c</fullName>
    <label>Outing</label>
    <referenceTo>Outing__c</referenceTo>
    <relationshipLabel>Batters</relationshipLabel>
    <relationshipName>Batters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

bp-core/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bp-core/main/default/objects/Outing__c/Outing__c.object-meta.xml
<CustomObject>
    <label>Outing</label>
    <nameField>
        <label>Outing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Outing__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Outings</relationshipLabel>
    <relationshipName>Outings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

bp-core/main/default/objects/Outing__c/fields/Pitcher__c.field-meta.xml
<CustomField>
    <fullName>Pitcher__c</fullName>
    <label>Pitcher</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active Pitchers can participate in Outing</errorMessage>
        <filterItems>
            <field>Pitcher__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Pitchers who&#39;s status is active are permitted.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pitcher__c</referenceTo>
    <relationshipLabel>Outings</relationshipLabel>
    <relationshipName>Outings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

bp-core/main/default/objects/Pitch__c/Pitch__c.object-meta.xml
<CustomObject>
    <label>Pitch</label>
    <nameField>
        <displayFormat>Pitch-{0000}</displayFormat>
        <label>Pitch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pitches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Pitch__c/fields/Batter__c.field-meta.xml
<CustomField>
    <fullName>Batter__c</fullName>
    <label>Batter</label>
    <referenceTo>Batter__c</referenceTo>
    <relationshipLabel>Pitches</relationshipLabel>
    <relationshipName>Pitches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

bp-core/main/default/objects/Pitcher__c/Pitcher__c.object-meta.xml
<CustomObject>
    <label>Pitcher</label>
    <nameField>
        <label>Pitcher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pitchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bp-core/main/default/classes/Application.cls
public class Application {
    
	// Configure and create the UnitOfWorkFactory for this Application
	public static final fflib_Application.UnitOfWorkFactory UnitOfWork = 
		new fflib_Application.UnitOfWorkFactory(
				new List<SObjectType> { 
					Pitcher__c.SObjectType, 
					Game__c.SObjectType, 
				  	Outing__c.SObjectType, 
				  	Batter__c.SObjectType,
                    Pitch__c.SObjectType });
    
    /**
     * Utility method to throw Application exceptions to Lightning Components
     **/
    public static void throwAuraHandledException(Exception e) {
        String message = e.getMessage();
        AuraHandledException error = new AuraHandledException(message);
        error.setMessage(message); // Ensure Apex tests can assert the error message value
        throw error;
    }
}