bp-core/main/default/objects/Batter__c/Batter__c.object-meta.xml
<CustomObject>
    <label>Batter</label>
    <nameField>
        <label>Batter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Batter__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>At Bat</fullName>
                <default>true</default>
                <label>At Bat</label>
            </value>
            <value>
                <fullName>Base Hit</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Hit By Pitch</fullName>
            </value>
            <value>
                <fullName>Put Out</fullName>
            </value>
            <value>
                <fullName>Strikeout</fullName>
            </value>
            <value>
                <fullName>Walk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

bp-core/main/default/objects/Pitch__c/Pitch__c.object-meta.xml
<CustomObject>
    <label>Pitch</label>
    <nameField>
        <displayFormat>Pitch-{0000}</displayFormat>
        <label>Pitch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pitches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Pitch__c/fields/Batter__c.field-meta.xml
<CustomField>
    <fullName>Batter__c</fullName>
    <label>Batter</label>
    <referenceTo>Batter__c</referenceTo>
    <relationshipLabel>Pitches</relationshipLabel>
    <relationshipName>Pitches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

bp-core/main/default/objects/Pitch__c/fields/Is_Strike__c.field-meta.xml
<CustomField>
    <fullName>Is_Strike__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Strike?</label>
    <type>Checkbox</type>
</CustomField>

bp-core/main/default/objects/Pitch__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type</label>
    <referenceTo>Pitch_Type__c</referenceTo>
    <relationshipLabel>Pitches</relationshipLabel>
    <relationshipName>Pitches</relationshipName>
    <type>Lookup</type>
</CustomField>

bp-core/main/default/objects/Pitch_Type__c/Pitch_Type__c.object-meta.xml
<CustomObject>
    <label>Pitch Type</label>
    <nameField>
        <label>Pitch Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pitch Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bp-core/main/default/classes/Pitches.cls
public inherited sharing class Pitches extends ApplicationDomain {

    public Pitches(List<Pitch__c> pitches) {
        super(pitches);
    }

    public override void onApplyDefaults(){

        Set<Id> pitchTypeIds = new Set<Id>();

        for (Pitch__c pitch : (List<Pitch__c>)Records) {
            pitchTypeIds.add(pitch.type__c);
        }

        Map<Id, Pitch_Type__c> associatedPitchTypes = new Map<Id, Pitch_Type__c>(new PitchTypesSelector().selectById(pitchTypeIds));

        for (Pitch__c pitch : (List<Pitch__c>)Records) {
            pitch.Is_Strike__c = associatedPitchTypes.get(pitch.type__c).Is_Strike__c;
        } 
    }

    public override void onValidate() {

        Map<Id, Batter__c> associatedBatters = new Map<Id, Batter__c>(this.queryAssociatedBatters((List<Pitch__c>)Records));

        for (Pitch__c pitch : (List<Pitch__c>)Records) {
            if (associatedBatters.get(pitch.batter__c).outcome__c != 'At Bat') {
                //raise error
                pitch.addError( 'Pitches can only be added to those currently at bat');		
            }
        }            
    }

    public override void onAfterInsert() {

		// Bulk load the associated batters
		Set<Id> batterIds = new Set<Id>();
		for(Pitch__c pitch : (List<Pitch__c>)Records) {
            batterIds.add(pitch.Batter__c);		    
		}			

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        Batters batters = new Batters(new BattersSelector().selectByIdWithPitchesWithPitchType(batterIds));
        batters.calculateCount(uow);

        uow.commitWork();
        
    }

	private List<Batter__c> queryAssociatedBatters(List<Pitch__c> pitches) {
		// Bulk load the associated batters
		Set<Id> batterIds = new Set<Id>();
		for(Pitch__c pitch : pitches) {
            batterIds.add(pitch.Batter__c);		    
		}			
		return new BattersSelector().selectById(batterIds);		
	}    

	public class Constructor implements fflib_SObjectDomain.IConstructable {
		public fflib_SObjectDomain construct(List<SObject> sObjectList) {
			return new Pitches(sObjectList);
		}
	}	    
}