bp-core/main/default/objects/Batter__c/Batter__c.object-meta.xml
<CustomObject>
    <label>Batter</label>
    <nameField>
        <label>Batter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Batter__c/fields/Count_Balls__c.field-meta.xml
<CustomField>
    <fullName>Count_Balls__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count Balls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bp-core/main/default/objects/Batter__c/fields/Count_Strikes__c.field-meta.xml
<CustomField>
    <fullName>Count_Strikes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count Strikes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bp-core/main/default/objects/Batter__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>At Bat</fullName>
                <default>true</default>
                <label>At Bat</label>
            </value>
            <value>
                <fullName>Base Hit</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Hit By Pitch</fullName>
            </value>
            <value>
                <fullName>Put Out</fullName>
            </value>
            <value>
                <fullName>Strikeout</fullName>
            </value>
            <value>
                <fullName>Walk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

bp-core/main/default/objects/Pitch__c/Pitch__c.object-meta.xml
<CustomObject>
    <label>Pitch</label>
    <nameField>
        <displayFormat>Pitch-{0000}</displayFormat>
        <label>Pitch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pitches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Pitch__c/fields/Batter__c.field-meta.xml
<CustomField>
    <fullName>Batter__c</fullName>
    <label>Batter</label>
    <referenceTo>Batter__c</referenceTo>
    <relationshipLabel>Pitches</relationshipLabel>
    <relationshipName>Pitches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

bp-core/main/default/objects/Pitch__c/fields/Is_Strike__c.field-meta.xml
<CustomField>
    <fullName>Is_Strike__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Strike?</label>
    <type>Checkbox</type>
</CustomField>

bp-core/main/default/objects/Pitch__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type</label>
    <referenceTo>Pitch_Type__c</referenceTo>
    <relationshipLabel>Pitches</relationshipLabel>
    <relationshipName>Pitches</relationshipName>
    <type>Lookup</type>
</CustomField>

bp-core/main/default/objects/Pitch_Type__c/Pitch_Type__c.object-meta.xml
<CustomObject>
    <label>Pitch Type</label>
    <nameField>
        <label>Pitch Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pitch Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bp-core/main/default/classes/Batters.cls
public inherited sharing class Batters extends ApplicationDomain {

    public Batters(List<Batter__c> batters) {
        super(batters);
    }

    
    public void calculateCount(fflib_ISObjectUnitOfWork uow) {

        for (Batter__c batter : (List<Batter__c>)Records) {
            batter.Count_Strikes__c = 0;
            batter.Count_Balls__c = 0;
            for (Pitch__c pitch : batter.pitches__r) {
                Pitch_Type__c pitchType = pitch.Type__r;
                if (pitch.Is_Strike__c) {
                    if (batter.Count_Strikes__c == 2 && pitchType.Name == 'Foul Ball') {
                        //don't increase count
                        //don't increase count
                    }
                    else {
                        batter.Count_Strikes__c++;
                    }
                    if (pitchType.Name == 'Foul Ball Caught') {
                        batter.Outcome__c = 'Put Out';
                    }
                }
                else {
                    batter.Count_Balls__c++;
                    if (batter.Count_Balls__c == 4) {
                        batter.Outcome__c = 'Walk';
                    }
                }
                
            }
            uow.registerDirty(batter);
        }

    }

    public void calculateCount() {

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        this.calculateCount(uow);

        uow.commitWork();
    }
}