bp-core/main/default/objects/Batter__c/Batter__c.object-meta.xml
<CustomObject>
    <label>Batter</label>
    <nameField>
        <label>Batter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Batter__c/fields/Balls_Thrown__c.field-meta.xml
<CustomField>
    <fullName>Balls_Thrown__c</fullName>
    <formula>Pitches_Thrown__c - Strikes_Thrown__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balls Thrown</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bp-core/main/default/objects/Batter__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>At Bat</fullName>
                <default>true</default>
                <label>At Bat</label>
            </value>
            <value>
                <fullName>Base Hit</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Hit By Pitch</fullName>
            </value>
            <value>
                <fullName>Put Out</fullName>
            </value>
            <value>
                <fullName>Strikeout</fullName>
            </value>
            <value>
                <fullName>Walk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

bp-core/main/default/objects/Batter__c/fields/Outing__c.field-meta.xml
<CustomField>
    <fullName>Outing__c</fullName>
    <label>Outing</label>
    <referenceTo>Outing__c</referenceTo>
    <relationshipLabel>Batters</relationshipLabel>
    <relationshipName>Batters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

bp-core/main/default/objects/Batter__c/fields/Pitches_Thrown__c.field-meta.xml
<CustomField>
    <fullName>Pitches_Thrown__c</fullName>
    <label>Pitches Thrown</label>
    <summaryForeignKey>Pitch__c.Batter__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

bp-core/main/default/objects/Batter__c/fields/Strikes_Thrown__c.field-meta.xml
<CustomField>
    <fullName>Strikes_Thrown__c</fullName>
    <label>Strikes Thrown</label>
    <summaryFilterItems>
        <field>Pitch__c.Is_Strike__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Pitch__c.Batter__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

bp-core/main/default/objects/Outing__c/Outing__c.object-meta.xml
<CustomObject>
    <label>Outing</label>
    <nameField>
        <label>Outing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Outing__c/fields/Balls_Thrown__c.field-meta.xml
<CustomField>
    <fullName>Balls_Thrown__c</fullName>
    <formula>Pitches_Thrown__c -  Strikes_Thrown__c</formula>
    <label>Balls Thrown</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bp-core/main/default/objects/Outing__c/fields/Pitches_Thrown__c.field-meta.xml
<CustomField>
    <fullName>Pitches_Thrown__c</fullName>
    <label>Pitches Thrown</label>
    <summarizedField>Batter__c.Pitches_Thrown__c</summarizedField>
    <summaryForeignKey>Batter__c.Outing__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

bp-core/main/default/objects/Outing__c/fields/Strikes_Thrown__c.field-meta.xml
<CustomField>
    <fullName>Strikes_Thrown__c</fullName>
    <label>Strikes Thrown</label>
    <summarizedField>Batter__c.Strikes_Thrown__c</summarizedField>
    <summaryForeignKey>Batter__c.Outing__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

bp-core/main/default/objects/Pitch__c/Pitch__c.object-meta.xml
<CustomObject>
    <label>Pitch</label>
    <nameField>
        <displayFormat>Pitch-{0000}</displayFormat>
        <label>Pitch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pitches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Pitch__c/fields/Batter__c.field-meta.xml
<CustomField>
    <fullName>Batter__c</fullName>
    <label>Batter</label>
    <referenceTo>Batter__c</referenceTo>
    <relationshipLabel>Pitches</relationshipLabel>
    <relationshipName>Pitches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

bp-core/main/default/objects/Pitch__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type</label>
    <referenceTo>Pitch_Type__c</referenceTo>
    <relationshipLabel>Pitches</relationshipLabel>
    <relationshipName>Pitches</relationshipName>
    <type>Lookup</type>
</CustomField>

bp-core/main/default/classes/BattersSelector.cls
public inherited sharing class BattersSelector extends ApplicationSelector {
    public BattersSelector() {

    }

    public List<Batter__c> selectById(Set<Id> batterIds) {
        return (List<Batter__c>)
            selectSObjectsById(batterIds);
    }

	public List<Batter__c> selectByIdWithPitches(Set<Id> batterIds) {
	    fflib_QueryFactory battersQueryFactory = newQueryFactory();
	    fflib_QueryFactory pitchesSubQueryFactory = new PitchesSelector().addQueryFactorySubselect(battersQueryFactory); 	    
        return (List<Batter__c>) Database.query(
            battersQueryFactory.setCondition('Id in :batterIds').toSOQL());
	}

    public List<Batter__c> selectByIdWithPitchesWithPitchType(Set<Id> batterIds) {
	    fflib_QueryFactory battersQueryFactory = newQueryFactory();  
        fflib_QueryFactory pitchesSubQueryFactory = new PitchesSelector().addQueryFactorySubselect(battersQueryFactory);  
        new PitchTypesSelector().configureQueryFactoryFields(pitchesSubQueryFactory, Pitch__c.Type__c.getDescribe().getRelationshipName());
    
        return (List<Batter__c>) Database.query(
            battersQueryFactory.setCondition('Id in :batterIds').toSOQL());
    }

    public List<Batter__c> selectByOuting(Set<Id> outingIds) {
        return (List<Batter__c>)
            Database.query(
                newQueryFactory().
                setCondition('Outing__c in :outingIds').
                toSOQL());
    }

    public List<Batter__c> selectByOutingWithPitches(Set<Id> outingIds) {
        fflib_QueryFactory battersQueryFactory = newQueryFactory();
        fflib_QueryFactory pitchesSubQueryFactory = new PitchesSelector().addQueryFactorySubselect(battersQueryFactory);
        return (List<Batter__c>) Database.query(
            battersQueryFactory.setCondition('Outing__c in :outingIds').toSOQL());
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Batter__c.Id,
            Batter__c.Name,
            Batter__c.Outing__c,
            Batter__c.Pitches_Thrown__c,
            Batter__c.Strikes_Thrown__c,
            Batter__c.Balls_Thrown__c,
            Batter__c.Outcome__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Batter__c.sObjectType;    
    }    
}