bp-core/main/default/objects/Batter__c/Batter__c.object-meta.xml
<CustomObject>
    <label>Batter</label>
    <nameField>
        <label>Batter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Pitch__c/Pitch__c.object-meta.xml
<CustomObject>
    <label>Pitch</label>
    <nameField>
        <displayFormat>Pitch-{0000}</displayFormat>
        <label>Pitch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pitches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bp-core/main/default/objects/Pitch__c/fields/Batter__c.field-meta.xml
<CustomField>
    <fullName>Batter__c</fullName>
    <label>Batter</label>
    <referenceTo>Batter__c</referenceTo>
    <relationshipLabel>Pitches</relationshipLabel>
    <relationshipName>Pitches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

bp-core/main/default/objects/Pitch__c/fields/Is_Strike__c.field-meta.xml
<CustomField>
    <fullName>Is_Strike__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Strike?</label>
    <type>Checkbox</type>
</CustomField>

bp-core/main/default/objects/Pitch__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type</label>
    <referenceTo>Pitch_Type__c</referenceTo>
    <relationshipLabel>Pitches</relationshipLabel>
    <relationshipName>Pitches</relationshipName>
    <type>Lookup</type>
</CustomField>

bp-core/main/default/classes/PitchesSelector.cls
public inherited sharing class PitchesSelector extends ApplicationSelector {
    public PitchesSelector() {

    }

    public List<Pitch__c> selectById(Set<ID> pitchIds) {
        return (List<Pitch__c>)
            selectSObjectsById(pitchIds);
    }

    public List<Pitch__c> selectByIdWithPitchType(Set<ID> pitchIds) {
	    fflib_QueryFactory pitchesQueryFactory = newQueryFactory();

        new PitchTypesSelector().configureQueryFactoryFields(pitchesQueryFactory, Pitch__c.Type__c.getDescribe().getRelationshipName());

        return Database.query(pitchesQueryFactory.setCondition('Id in :pitchIds').toSOQL());
    }

    public List<Pitch__c> selectByBatter(Set<ID> batterIds) {
        return (List<Pitch__c>)
            Database.query(
                newQueryFactory().
                setCondition('Batter__c in :batterIds').
                toSOQL());
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Pitch__c.Id,
            Pitch__c.Name,
            Pitch__c.Is_Strike__c,
            Pitch__c.Batter__c,
            Pitch__c.Type__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Pitch__c.sObjectType;    
    }
}